{
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [
      {
        "children": [],
        "cpe_match": [
          {
            "cpe23Uri": "cpe:2.3:a:gnome:libpeas:*:*:*:*:*:*:*:*",
            "cpe_name": [],
            "versionEndExcluding": "0.5.3",
            "vulnerable": true
          }
        ],
        "operator": "OR"
      },
      {
        "children": [],
        "cpe_match": [
          {
            "cpe23Uri": "cpe:2.3:o:fedoraproject:fedora:9:*:*:*:*:*:*:*",
            "cpe_name": [],
            "vulnerable": true
          }
        ],
        "operator": "OR"
      }
    ]
  },
  "cve": {
    "CVE_data_meta": {
      "ASSIGNER": "cve@mitre.org",
      "ID": "CVE-2009-0314"
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "Untrusted search path vulnerability in the Python module in gedit allows local users to execute arbitrary code via a Trojan horse Python file in the current working directory, related to a vulnerability in the PySys_SetArgv function (CVE-2008-5983)."
        }
      ]
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [
            {
              "lang": "en",
              "value": "CWE-426"
            }
          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "name": "http://bugzilla.gnome.org/show_bug.cgi?id=569214",
          "refsource": "MISC",
          "tags": [
            "Exploit",
            "Issue Tracking",
            "Patch",
            "Vendor Advisory"
          ],
          "url": "http://bugzilla.gnome.org/show_bug.cgi?id=569214"
        },
        {
          "name": "[oss-security] 20090126 CVE request -- Python \u003c 2.6 PySys_SetArgv issues (epiphany, csound, dia, eog, gedit, xchat, vim, nautilus-python, Gnumeric)",
          "refsource": "MLIST",
          "tags": [
            "Mailing List"
          ],
          "url": "http://www.openwall.com/lists/oss-security/2009/01/26/2"
        },
        {
          "name": "https://bugzilla.redhat.com/show_bug.cgi?id=481556",
          "refsource": "CONFIRM",
          "tags": [
            "Exploit",
            "Issue Tracking",
            "Patch",
            "Third Party Advisory"
          ],
          "url": "https://bugzilla.redhat.com/show_bug.cgi?id=481556"
        },
        {
          "name": "33769",
          "refsource": "SECUNIA",
          "tags": [
            "Third Party Advisory"
          ],
          "url": "http://secunia.com/advisories/33769"
        },
        {
          "name": "FEDORA-2009-1189",
          "refsource": "FEDORA",
          "tags": [
            "Third Party Advisory"
          ],
          "url": "https://www.redhat.com/archives/fedora-package-announce/2009-January/msg01195.html"
        },
        {
          "name": "33759",
          "refsource": "SECUNIA",
          "tags": [
            "Third Party Advisory"
          ],
          "url": "http://secunia.com/advisories/33759"
        },
        {
          "name": "33445",
          "refsource": "BID",
          "tags": [
            "Third Party Advisory",
            "VDB Entry"
          ],
          "url": "http://www.securityfocus.com/bid/33445"
        },
        {
          "name": "34522",
          "refsource": "SECUNIA",
          "tags": [
            "Third Party Advisory"
          ],
          "url": "http://secunia.com/advisories/34522"
        },
        {
          "name": "GLSA-200903-41",
          "refsource": "GENTOO",
          "tags": [
            "Third Party Advisory"
          ],
          "url": "http://security.gentoo.org/glsa/glsa-200903-41.xml"
        },
        {
          "name": "MDVSA-2009:039",
          "refsource": "MANDRIVA",
          "tags": [
            "Third Party Advisory"
          ],
          "url": "http://www.mandriva.com/security/advisories?name=MDVSA-2009:039"
        },
        {
          "name": "gedit-pysyssetargv-privilege-escalation(48271)",
          "refsource": "XF",
          "tags": [
            "Third Party Advisory",
            "VDB Entry"
          ],
          "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/48271"
        }
      ]
    }
  },
  "impact": {
    "baseMetricV2": {
      "acInsufInfo": false,
      "cvssV2": {
        "accessComplexity": "MEDIUM",
        "accessVector": "LOCAL",
        "authentication": "NONE",
        "availabilityImpact": "COMPLETE",
        "baseScore": 6.9,
        "confidentialityImpact": "COMPLETE",
        "integrityImpact": "COMPLETE",
        "vectorString": "AV:L/AC:M/Au:N/C:C/I:C/A:C",
        "version": "2.0"
      },
      "exploitabilityScore": 3.4,
      "impactScore": 10,
      "obtainAllPrivilege": true,
      "obtainOtherPrivilege": false,
      "obtainUserPrivilege": false,
      "severity": "MEDIUM",
      "userInteractionRequired": true
    }
  },
  "lastModifiedDate": "2020-06-15T17:38Z",
  "publishedDate": "2009-01-28T11:30Z"
}