{
  "Identifier": "CVE-2020-1740",
  "PackageSlug": "pypi/ansible",
  "Title": "Information Exposure",
  "Description": "A flaw was found in Ansible Engine when using Ansible Vault for editing encrypted files. When a user executes `ansible-vault edit`, another user on the same computer can read the old and new secret, as it is created in a temporary file with mkstemp and the returned file descriptor is closed and the method write_data is called to write the existing secret in the file. This method will delete the file before recreating it insecurely.",
  "Date": "2021-08-07",
  "Pubdate": "2020-03-16",
  "AffectedRange": "\u003c=2.7.16||\u003e=2.8.0,\u003c=2.8.8||\u003e=2.9.0,\u003c=2.9.5",
  "FixedVersions": [
    "2.7.17",
    "2.8.9",
    "2.9.6"
  ],
  "AffectedVersions": "All versions up to 2.7.16, all versions starting from 2.8.0 up to 2.8.8, all versions starting from 2.9.0 up to 2.9.5",
  "NotImpacted": "All versions after 2.7.16 before 2.8.0, all versions after 2.8.8 before 2.9.0, all versions after 2.9.5",
  "Solution": "Upgrade to versions 2.7.17, 2.8.9, 2.9.6 or above.",
  "Urls": [
    "https://nvd.nist.gov/vuln/detail/CVE-2020-1740",
    "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2020-1740"
  ],
  "CvssV2": "AV:L/AC:M/Au:N/C:P/I:N/A:N",
  "CvssV3": "CVSS:3.1/AV:L/AC:H/PR:L/UI:N/S:U/C:H/I:N/A:N",
  "UUID": "83300929-1e97-49ef-99f8-87abb761b8ea"
}