{
  "Identifier": "CVE-2025-58446",
  "PackageSlug": "pypi/xgrammar",
  "Title": "xgrammar vulnerable to denial of service by huge enum grammar",
  "Description": "Provided grammar, would fit in a context window of most of the models, but takes minutes to process in 0.1.23. In testing with 0.1.16 the parser worked fine so this seems to be a regression caused by Earley parser.",
  "Date": "2025-09-10",
  "Pubdate": "2025-09-05",
  "AffectedRange": "\u003e=0.1.23,\u003c0.1.24||==0.1.23",
  "FixedVersions": [
    "0.1.24"
  ],
  "AffectedVersions": "All versions starting from 0.1.23 before 0.1.24, version 0.1.23",
  "NotImpacted": "",
  "Solution": "Upgrade to version 0.1.24 or above.",
  "Urls": [
    "https://nvd.nist.gov/vuln/detail/CVE-2025-58446",
    "https://github.com/advisories/GHSA-9q5r-wfvf-rr7f",
    "https://github.com/mlc-ai/xgrammar/security/advisories/GHSA-9q5r-wfvf-rr7f",
    "https://github.com/mlc-ai/xgrammar/commit/ced69c3ad2f8f61b516cc278a342e7c644383e27",
    "https://github.com/mlc-ai/xgrammar"
  ],
  "CvssV2": "",
  "CvssV3": "",
  "UUID": "c3e2f24e-8504-42c8-b3b5-25bbd1c36c28"
}