{
  "Title": "Security update for python-rpyc",
  "Tracking": {
    "ID": "openSUSE-SU-2024:0082-1",
    "Status": "Final",
    "Version": "1",
    "InitialReleaseDate": "2024-03-15T16:00:10Z",
    "CurrentReleaseDate": "2024-03-15T16:00:10Z",
    "RevisionHistory": [
      {
        "Number": "1",
        "Date": "2024-03-15T16:00:10Z",
        "Description": "current"
      }
    ]
  },
  "Notes": [
    {
      "Text": "Security update for python-rpyc",
      "Title": "Topic",
      "Type": "Summary"
    },
    {
      "Text": "This update for python-rpyc fixes the following issues:\n\n- CVE-2024-27758: Fixed remote code execution via exposed methods (boo#1221331).\n",
      "Title": "Details",
      "Type": "General"
    },
    {
      "Text": "The CVRF data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
      "Title": "Terms of Use",
      "Type": "Legal Disclaimer"
    },
    {
      "Text": "openSUSE-2024-82",
      "Title": "Patchnames",
      "Type": "Details"
    }
  ],
  "ProductTree": {
    "Relationships": [
      {
        "ProductReference": "python3-rpyc-4.1.5-bp155.3.3.1",
        "RelatesToProductReference": "SUSE Package Hub 15 SP5",
        "RelationType": "Default Component Of"
      },
      {
        "ProductReference": "python3-rpyc-4.1.5-bp155.3.3.1",
        "RelatesToProductReference": "openSUSE Leap 15.5",
        "RelationType": "Default Component Of"
      }
    ]
  },
  "References": [
    {
      "URL": "https://lists.opensuse.org/archives/list/security-announce@lists.opensuse.org/thread/AQXPI4PTGO5Y3OJPY3PCERYEYZAUX2VW/",
      "Description": "E-Mail link for openSUSE-SU-2024:0082-1"
    },
    {
      "URL": "https://www.suse.com/support/security/rating/",
      "Description": "SUSE Security Ratings"
    },
    {
      "URL": "https://bugzilla.suse.com/1221331",
      "Description": "SUSE Bug 1221331"
    },
    {
      "URL": "https://www.suse.com/security/cve/CVE-2024-27758/",
      "Description": "SUSE CVE CVE-2024-27758 page"
    }
  ],
  "Vulnerabilities": [
    {
      "CVE": "CVE-2024-27758",
      "Description": "** RESERVED ** This candidate has been reserved by an organization or individual that will use it when announcing a new security problem. When the candidate has been publicized, the details for this candidate will be provided.",
      "Threats": [
        {
          "Type": "Impact",
          "Severity": "important"
        }
      ],
      "References": [
        {
          "URL": "https://www.suse.com/security/cve/CVE-2024-27758.html",
          "Description": "CVE-2024-27758"
        },
        {
          "URL": "https://bugzilla.suse.com/1221331",
          "Description": "SUSE Bug 1221331"
        }
      ],
      "ProductStatuses": [
        {
          "Type": "Fixed",
          "ProductID": [
            "SUSE Package Hub 15 SP5:python3-rpyc-4.1.5-bp155.3.3.1",
            "openSUSE Leap 15.5:python3-rpyc-4.1.5-bp155.3.3.1"
          ]
        }
      ],
      "CVSSScoreSets": {}
    }
  ]
}