{
  "Identifier": "CVE-2017-12863",
  "PackageSlug": "pypi/opencv-python",
  "Title": "Integer Overflow or Wraparound",
  "Description": "In opencv/modules/imgcodecs/src/grfmt_pxm.cpp, function PxMDecoder::readData has an integer overflow when calculate src_pitch. If the image is from remote, may lead to remote code execution or denial of service. This affects Opencv.",
  "Date": "2021-11-18",
  "Pubdate": "2021-10-12",
  "AffectedRange": "\u003c=3.3.0.9",
  "FixedVersions": [
    "3.3.1.11"
  ],
  "AffectedVersions": "All versions up to 3.3.0.9",
  "NotImpacted": "All versions after 3.3.0.9",
  "Solution": "Upgrade to version 3.3.1.11 or above.",
  "Urls": [
    "https://nvd.nist.gov/vuln/detail/CVE-2017-12863",
    "https://github.com/opencv/opencv/issues/9371",
    "https://github.com/opencv/opencv/pull/9376",
    "https://lists.debian.org/debian-lts-announce/2018/07/msg00030.html",
    "https://security.gentoo.org/glsa/201712-02",
    "https://lists.debian.org/debian-lts-announce/2021/10/msg00028.html",
    "https://github.com/advisories/GHSA-wq8f-wvqp-xvvm"
  ],
  "CvssV2": "AV:N/AC:M/Au:N/C:P/I:P/A:P",
  "CvssV3": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
  "UUID": "56125de5-5fc2-4636-a636-95a93c15d14f"
}